name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run cargo-doc
      run: cargo doc --all --no-deps
    - name: GitHub Pages
      # You may pin to the exact commit or the version.
      # uses: crazy-max/ghaction-github-pages@a117e4aa1fb4854d021546d2abdfac95be568a3a
      uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        # Git branch where assets will be deployed
        target_branch: gh-pages
        # Create incremental commit instead of doing push force
        keep_history: false
        # Allow an empty commit to be created
        allow_empty_commit: true
        # Build directory to deploy
        build_dir: target/doc
        # Whether to treat build_dir as an absolute path
        absolute_build_dir: false
        # If enabled, the content of symbolic links will be copied
        follow_symlinks: false
        # Commit message
        commit_message: update blog
        # Write the given domain name to the CNAME file
        fqdn: rustacean.org
        # Allow Jekyll to build your site
        jekyll: false
        # If enabled, nothing will be pushed
        dry_run: false
        # Enable verbose output
        verbose: false
